### PR TITLE
Fix target_cxx_version for interface targets

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
This fixes adding cxx versions for interface targets for older version of cmake (aka Kinetic builds).

@mpowelson Ready to review.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
If the xenial build [here](https://github.com/Levi-Armstrong/descartes_light/actions/runs/164653301) passes then this worked.

**Comment by mpowelson** [comment]
Ok. I am also a bit concerned that [this](https://github.com/ros-industrial-consortium/tesseract/runs/858053384?check_suite_focus=true) failed. I am wondering if the opw kinematics C++11 is somehow overwriting the C++14 that PCL needs

**Comment by mpowelson** [comment]
Specifically see here https://github.com/ros-industrial-consortium/tesseract/runs/858053384?check_suite_focus=true#step:6:936

**Comment by Levi-Armstrong** [comment]
I had one issue in descartes cmake file everything passes now shown [here](https://github.com/Levi-Armstrong/descartes_light/actions/runs/164666807)

**Comment by Levi-Armstrong** [comment]
https://github.com/swri-robotics/descartes_light/pull/24

**Comment by Levi-Armstrong** [comment]
Did this every pass before? I expect we may be not correctly adding pcl compiler options and definitions which may have changed for pcl 1.10.

**Comment by mpowelson** [comment]
The cron build passed yesterday morning before we merged the opw kinematics PR. https://github.com/ros-industrial-consortium/tesseract/actions/runs/162829542

**Pull request merged**
