### PR TITLE
Update default IWYU args

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@mpowelson Ready to review.

**Comment by mpowelson** [comment]
On vtk_viewer it still doesn't show any problems. But maybe there aren't any.

**Comment by mpowelson** [comment]
For reference, the problem was that I did not have the proper version of clang installed, and it is apparently not a debian dependency. If you don't have it, it looks like it silently does nothing.

Check the version you need with `iwyu --version` and apt install it. For Focal, this is 
```
sudo apt install iwyu
sudo apt install clang-9
```

**Comment by Levi-Armstrong** [comment]
Addressed by #5

**Pull request closed without merging**
